#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
# *
# * $Id:$
# *
# * HISTORIQUE
# *
# * MOD : VERSION : 1.0 : Creation
# *
# * FIN-HISTORIQUE
# *
# *


# MAJA version
MAJA_VERSION_MAJOR = "@MAJA_VERSION_MAJOR@"
MAJA_VERSION_MINOR = "@MAJA_VERSION_MINOR@"
MAJA_VERSION_PATCH = "@MAJA_VERSION_PATCH@"
MAJA_VERSION = "@MAJA_VERSION@"

MAJA_VERSION_LOGGER_STRING = "@MAJA_VERSION_LOGGER_STRING@"